drop table if exists user CASCADE;
create table user
(
    id bigint not null auto_increment,
#     id bigint generated by default as identity,
    name varchar(255),
    nickname varchar(255),
    primary key (id)
);

